apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
        type: database
    spec:
      containers:
        - name: cont-redis
          image: redis
          ports:
            - containerPort: 80
